### ISSUE TITLE
Installation of PyQt5

### ISSUE THREAD

**Issue by faymanns** [NeLy-EPFL/DeepFly3D#21]
This is not a DeepFly3D issue but I will document it here for future reference.
Running `pip install .` can cause an error when pip tries to install PyQt5.
The error message looks something like this:
```
    ERROR: Complete output from command /home/aymanns/.conda/envs/deepflyfront/bin/python /home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpmldfr5gc:
    ERROR: Querying qmake about your Qt installation...
    /usr/bin/qmake -query
    Traceback (most recent call last):
      File "/home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 64, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 67, in prepare_metadata_for_build_wheel
        config_settings)
      File "/home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 95, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/sipbuild/abstract_project.py", line 82, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 387, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 62, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/pyqtbuild/project.py", line 86, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 202, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/pyqtbuild/builder.py", line 76, in apply_user_defaults
        self._get_qt_configuration()
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/pyqtbuild/builder.py", line 431, in _get_qt_configuration
        for line in project.read_command_pipe([self.qmake, '-query']):
      File "/tmp/pip-build-env-mh0ik_qb/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 350, in read_command_pipe
        raise UserException("'{0}' failed returning {1}".format(cmd, rc))
    sipbuild.exceptions.UserException
    ----------------------------------------
ERROR: Command "/home/aymanns/.conda/envs/deepflyfront/bin/python /home/aymanns/.conda/envs/deepflyfront/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpmldfr5gc" failed with error code 1 in /tmp/pip-install-zq8org3n/PyQt5

```

**Comment by faymanns** [comment]
A work around is to install PyQt with conda using `conda install -c anaconda pyqt` and then installing DeepFly3D with pip.
