### ISSUE TITLE
Wrong assumption about default for zero padding of image files

### ISSUE THREAD

**Issue by faymanns** [NeLy-EPFL/DeepFly3D#23]
This issue concerns the front branch.

When opening the GUI with the `df3d path/to/image/folder/` and error with the following traceback is raise if the folder contains images without zero padding.

```
Traceback (most recent call last):
File "/home/aymanns/.conda/envs/df3dfork/bin/df3d", line 11, in <module>
load_entry_point('deepfly', 'console_scripts', 'df3d')()
File "/home/aymanns/DeepFly3DFork/deepfly/gui.py", line 18, in main
window.setup(**cli_args)
File "/home/aymanns/DeepFly3DFork/deepfly/gui.py", line 63, in setup
self.core = Core(input_folder, output_subfolder, num_images_max)
File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 71, in __init__
self.check_cameras()
File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 523, in check_cameras
cam_missing = [cam.cam_id for cam in self.camNetAll.cam_list if cam.is_empty()]
File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 523, in <listcomp>
cam_missing = [cam.cam_id for cam in self.camNetAll.cam_list if cam.is_empty()]
File "/home/aymanns/DeepFly3DFork/deepfly/Camera.py", line 97, in is_empty
has_images = self.get_image(img_id=0) is not None
File "/home/aymanns/DeepFly3DFork/deepfly/Camera.py", line 203, in get_image
raise FileNotFoundError
FileNotFoundError
```

**Comment by semihgunel** [comment]
I don't think the problem is zero paddings in the names, df3d reads both types of filenames. This exception can be thrown if some cameras are missing.

**Comment by faymanns** [comment]
It's supposed to read both types of filenames but the front branch doesn't because of a bug.

This is the function that is supposed to return the images:
https://github.com/NeLy-EPFL/DeepFly3D/blob/8536464320571a0d28c76d3905d5039d7fa097a6/deepfly/Camera.py#L187-L216

As you can see it calls `constr_img_name` twice to get the image names, one time with no `pad` argument and the other time with `pad=True`. This assumes that the default of the `pad` is `False`.
However, the default is `True`:
https://github.com/NeLy-EPFL/DeepFly3D/blob/8536464320571a0d28c76d3905d5039d7fa097a6/deepfly/os_util.py#L37-L41

I fixed this bug in the pull-request above by explicitly setting `pad=False`:
441bbc6f825bb8ef3fa7cb366090b09eec6cb4df

**Comment by semihgunel** [comment]
I see. I pushed my changes. I think the commit 7cc616a should solve it.
