### ISSUE TITLE
Front Branch: Index out of bounds exception when moving to next error in GUI

### ISSUE THREAD

**Issue by faymanns** [NeLy-EPFL/DeepFly3D#25]
When you click on "next error" in the correction mode of the GUI the following index out of bounds
error is raise.
I suspect this only happens when no errors are detected but haven't tested it.
```
df3d /mnt/data/CLC/190703_SS42740-tdTomGC6fopt/Fly2/CO2xzGG/behData_002/images/ --output-folder df3d_2
/mnt/data/CLC/190703_SS42740-tdTomGC6fopt/Fly2/CO2xzGG/behData_002/images
(df3dfork) aymanns@upramdyapc1:~$ df3d /mnt/data/CLC/190703_SS42740-tdTomGC6fopt/Fly2/CO2xzGG/behData_002/images/ --output-folder df3d_2
/mnt/data/CLC/190703_SS42740-tdTomGC6fopt/Fly2/CO2xzGG/behData_002/images
Finished Belief Propagation
Finished Belief Propagation
Traceback (most recent call last):
  File "/home/aymanns/DeepFly3DFork/deepfly/gui.py", line 246, in onclick_next_error
    next_img = self.core.next_error(self.img_id)
  File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 181, in next_error
    return self.next_error_in_range(range(img_id + 1, self.max_img_id + 1))
  File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 537, in next_error_in_range
    if self.joint_has_error(img_id, joint_id):
  File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 568, in joint_has_error
    err_left = get_error(img_id, joint_id, self.camNetLeft)
  File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 553, in get_joint_reprojection_error
    [cam.points2d[img_id, joint_id, :] for cam in visible_cameras]
  File "/home/aymanns/DeepFly3DFork/deepfly/core.py", line 553, in <listcomp>
    [cam.points2d[img_id, joint_id, :] for cam in visible_cameras]
IndexError: index 150 is out of bounds for axis 0 with size 150
Aborted (core dumped)
```

**Comment by faymanns** [comment]
This is caused by a mismatch between the number of processed images and the number of image in the folder. I suggest there should be a user warning and the number of image in correction mode should be limited to the number of processed images.

**Comment by semihgunel** [comment]
Currently, I cannot reproduce this.
